#!/bin/bash

chmod +x ~/binder/start.neo4j 
chmod +x ~/binder/start.vscode 
chmod +x ~/binder/start.postgres
chmod +x ~/binder/start.redis

# starting neo4j
~/binder/start.neo4j   &

# starting vscode in parallel
~/binder/start.vscode   &

# starting postgresql
~/binder/start.postgres

# starting redis
~/binder/start.redis &

# adding my own extensions
mkdir -p ~/.ipython/extensions/
cp ~/.ipython/extensions/* ~/.ipython/extensions/

# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"